### ISSUE TITLE
And should be used for Allow, Or for Deny

### ISSUE THREAD

**Issue by klizhentas** [gravitational/rbac-linter#7]
In Teleport's RBAC for allow rule to apply, all labels should match for Allow rule to apply, and Any label could match for Deny rule to apply:

https://github.com/gravitational/rbac-linter/blob/2e64c6e437f2309cbd16b4859bb39d6b73807360/role_analyzer.py#L426

So this above should be tweaked for allow and deny rules

**Comment by ahelwer** [comment]
Oops that's an embarrassing oversight! Probably best done by moving the logic in `matches_constraint_group` up into the `allows` function, or having `matches_constraint_group` return a list of individual constraints that the `allows` function can fold with an `z3.And` or `z3.Or` (would probably want to rename `matches_constraint_group` in that case).

**Comment by ahelwer** [comment]
Quick fix, added `z3.And` or `z3.Or` as a higher-order parameter to the functions. Proposed solution in above comment wouldn't work because actually the affected logic is two nested functions down, in `matches_constraints`.
